config:
  format_version: 3

collected_material_photo:
  structure:
    2:
      uid_cm: [datatype(UUID), join("collected_material")]
      uid_photo: [datatype(UUID), uid_file(), file_assigned_to("collected_material")]
      description: [datatype(VARCHAR), describes_file(uid_photo)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default(null)]
    1:
      uid_cm: [datatype(UUID), join("collected_material")]
      uid_photo: [datatype(UUID), uid_file(), file_location_for("collected_material")]
      description: [datatype(VARCHAR), describes_file(uid_photo)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default('Null')]
  migration:
    2:
      upgrade:
        - alter("modified_by")
